### ISSUE TITLE
Duplicated procedures defined in submodules *.i90

### ISSUE THREAD

**Issue by pmartorell** [Fortran-FOSS-Programmers/ford#250] opened 2018-09-04 08:09 UTC
I found that when a procedure is defined in another file through `#include` statement the procedure is duplicated in the procedure's section of the FORD documentation. Here a dummy example:

Main module `module.f90`:

```fortran
module module_name
  type my_test
  contains
    procedure :: test_procedure
  end type my_test
contains
#include "submodule.i90"
end module module_name
```
Where the `submodule.i90` contains the following:

```fortran
subroutine test_procedure (this)
class(my_test), intent(inout) :: this
end subroutine test_procedure
```  

Then, the `test_procedure` is duplicated as follows:
![image](https://user-images.githubusercontent.com/37292905/45017463-f2e35d00-b027-11e8-8e68-5459173de5ab.png)

If `source: true` only the first instance of `test_procedure` contains the highlighted source code.

Is it possible to merge the repeated procedures in the documentation?

**Comment by cmacmackin** [comment] 2018-09-04 10:27
This is a duplicate of the issue in #119.

**Closed by cmacmackin** 2018-09-04 10:27 UTC
Labels: duplicate
