### ISSUE TITLE
Webpage link in autodoc comment

### ISSUE THREAD

**Issue by patflynngithub** [Fortran-FOSS-Programmers/ford#500] opened 2023-04-02 16:31 UTC
When I put a webpage address (e.g. http://www.weblink.com) in an autodoc comment, it cuts off at the colon in the URL. This happens both on the first and later lines of the comments. I've tried escaping and the []() markdown option. I finally figured out that the colon cutoff won't happen if I put the URL in double quotes, but the quotes display in the FORD doc w/o a link. Same thing happens using the \[\]\(\) markdown syntax, but the underlying link is to the FORD-doc page that I'm on.

I can go with the double quote option (w/o the \[\]\(\) markdown syntax), but it's kinda annoying.

**Comment by ZedThree** [comment] 2023-04-03 08:17
Sorry you're having this problem @patflynngithub. What version of Ford are you using? Please could you also give an example that reproduces the problem? I just had a quick try with the latest version (6.2.3) and it works for me, using both `<http://www.example.com>` and `[example](http://www.example.com)` syntax:

```ford
module ford_example_type_mod
  !! Summary of this module <http://www.example.com>
  !!
  !! A longer description of the purpose of this module
  !! [example](http://www.example.com>)
```

**Comment by patflynngithub** [comment] 2023-04-03 17:15
I'm using FORD version 6.1.17. Thinking it extremely unlikely that this fairly recent version is the problem, after your response, the idea occurred to me that the preprocessor could be causing the problem. We use *pcpp* (C preprocessor written in Python) locally on our Windows PCs for reasons that I will not go into. So, I logged into one of our online Linux servers to have FORD use the standard preprocessor instead (eliminated the *processor: pcpp* line in the FORD project file). It worked!

Back on my PC, I added the **--passthru-comments** *pcpp* command-line option to the *processor: pcpp* line. This worked as well.

I'm not sure what's going on here, but it works!

**Comment by ZedThree** [comment] 2023-04-04 08:04
Ah, that's interesting! I've been thinking about adding `pcpp` as the default option for the preprocessor so that ford can just work out of the box on any system. Useful to know we'd need to add some options as well!

I'll close this issue now, but feel free to re-open it if there's still a problem

**Closed by ZedThree** 2023-04-04 08:04 UTC
