### ISSUE TITLE
Submodules lead to a crash - 'FortranModule' object has no attribute 'all_absinterfaces' 

### ISSUE THREAD

**Issue by arjenmarkus** [Fortran-FOSS-Programmers/ford#322] opened 2021-03-25 14:47 UTC
In a thread on the Intel Fortran forum Daniel Dopico reported a failure in FORD when handling submodules. I got a small example to reproduce this problem, 
[problem_submodules.zip](https://github.com/Fortran-FOSS-Programmers/ford/files/6205561/problem_submodules.zip)

The error message is shown in the title.

**Comment by ZedThree** [comment] 2021-07-14 13:25
I can't reproduce this in current master, so I'm going to close this. Please reopen the issue if it is still a problem!

**Closed by ZedThree** 2021-07-14 13:25 UTC
Labels: bug
